services:
  miniostorage:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      # TODO: Set your own storage config
      - Storage__Endpoint=minio-nginx:9000
      - Storage__DefaultBucketName=local-bucket
      - Storage__AccessKey=mcj4xERVv28qOClNvgac
      - Storage__SecretKey=5KqDfaeQ8ZH18RN36rxHvLKCFSTLrImwnwYYycSF
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro